import { workbenchContent } from "../../../../content";

export function getEchartsTheme() {
  const isDark =
    typeof document !== "undefined" && document.documentElement.classList.contains("dark");

  const visuals = workbenchContent().dashboard;
  const colors = visuals.themeColors(isDark);
  const textColor = colors.text;
  const textColorSecondary = colors.textSecondary;
  const axisColor = colors.axis;
  const splitLineColor = colors.splitLine;
  const borderColor = colors.border;

  return {
    seriesCnt: "3",
    backgroundColor: "rgba(0, 0, 0, 0)",
    titleColor: textColor,
    subtitleColor: textColorSecondary,
    textColorShow: false,
    textColor: textColor,
    markTextColor: "#eee",
    color: [...visuals.series],
    borderColor: borderColor,
    borderWidth: 0,
    visualMapColor: [...colors.visualMap],
    legendTextColor: textColorSecondary,
    kColor: "#eb5454",
    kColor0: colors.kPositive,
    kBorderColor: "#eb5454",
    kBorderColor0: colors.kPositive,
    kBorderWidth: 1,
    lineWidth: 2,
    symbolSize: 4,
    symbol: "emptyCircle",
    symbolBorderWidth: 1,
    lineSmooth: false,
    graphLineWidth: 1,
    graphLineColor: "#aaa",
    mapLabelColor: "#000",
    mapLabelColorE: "rgb(100,0,0)",
    mapBorderColor: "#444",
    mapBorderColorE: "#444",
    mapBorderWidth: 0.5,
    mapBorderWidthE: 1,
    mapAreaColor: "#eee",
    mapAreaColorE: "rgba(255,215,0,0.8)",
    axes: [
      {
        type: "all",
        name: "General Axis",
        axisLineShow: true,
        axisLineColor: axisColor,
        axisTickShow: true,
        axisTickColor: axisColor,
        axisLabelShow: true,
        axisLabelColor: axisColor,
        splitLineShow: true,
        splitLineColor: [splitLineColor],
        splitAreaShow: false,
        splitAreaColor: ["rgba(250,250,250,0.2)", "rgba(210,219,238,0.2)"],
      },
      {
        type: "category",
        name: "Category Axis",
        axisLineShow: true,
        axisLineColor: axisColor,
        axisTickShow: true,
        axisTickColor: axisColor,
        axisLabelShow: true,
        axisLabelColor: axisColor,
        splitLineShow: false,
        splitLineColor: [splitLineColor],
        splitAreaShow: false,
        splitAreaColor: ["rgba(250,250,250,0.2)", "rgba(210,219,238,0.2)"],
      },
      {
        type: "value",
        name: "Value Axis",
        axisLineShow: false,
        axisLineColor: axisColor,
        axisTickShow: false,
        axisTickColor: axisColor,
        axisLabelShow: true,
        axisLabelColor: axisColor,
        splitLineShow: true,
        splitLineColor: [splitLineColor],
        splitAreaShow: false,
        splitAreaColor: ["rgba(250,250,250,0.2)", "rgba(210,219,238,0.2)"],
      },
      {
        type: "log",
        name: "Log Axis",
        axisLineShow: false,
        axisLineColor: axisColor,
        axisTickShow: false,
        axisTickColor: axisColor,
        axisLabelShow: true,
        axisLabelColor: axisColor,
        splitLineShow: true,
        splitLineColor: [splitLineColor],
        splitAreaShow: false,
        splitAreaColor: ["rgba(250,250,250,0.2)", "rgba(210,219,238,0.2)"],
      },
      {
        type: "time",
        name: "Time Axis",
        axisLineShow: true,
        axisLineColor: axisColor,
        axisTickShow: true,
        axisTickColor: axisColor,
        axisLabelShow: true,
        axisLabelColor: axisColor,
        splitLineShow: false,
        splitLineColor: [splitLineColor],
        splitAreaShow: false,
        splitAreaColor: ["rgba(250,250,250,0.2)", "rgba(210,219,238,0.2)"],
      },
    ],
    axisSeperateSetting: true,
    toolboxColor: "#999",
    toolboxEmphasisColor: "#666",
    tooltipAxisColor: borderColor,
    tooltipAxisWidth: 1,
    timelineLineColor: colors.timelineLine,
    timelineLineWidth: 2,
    timelineItemColor: colors.timelineAccent,
    timelineItemColorE: "#FFF",
    timelineCheckColor: colors.timelineCheck,
    timelineCheckBorderColor: "#fff",
    timelineItemBorderWidth: 1,
    timelineControlColor: colors.timelineAccent,
    timelineControlBorderColor: colors.timelineAccent,
    timelineControlBorderWidth: 1,
    timelineLabelColor: colors.timelineAccent,
    gridLeft: "10%",
    gridRight: "10%",
    gridTop: 60,
    gridBottom: 70,
    legendLeft: "center",
    legendRight: "",
    legendTop: 0,
    legendBottom: "",
  };
}
