import type { ManagerPresentation } from "@ontomato/ontology-manager";

/**
 * Open-source Manager presentation values (b6437c86), handed to the component by the profile. The theme variables are the
 * product-specific brand and neutral colours (effective light/dark values of the original web/src/styles/theme.css and the
 * Element Plus variables under the Manager theme rules); the rest are component-specific properties.
 */
export const ossPresentation: ManagerPresentation = {
  themeProperties: {
    light: {
      "--el-color-primary": "rgb(99, 156, 45)",
      "--el-color-primary-light-3": "#92ba6c",
      "--el-color-primary-light-5": "#b1ce96",
      "--el-color-primary-light-7": "#d0e1c0",
      "--el-color-primary-light-8": "#e0ebd5",
      "--el-color-primary-light-9": "#eff5ea",
      "--el-color-primary-dark-2": "#4f7d24",
      "--el-color-success": "#63a33e",
      "--el-color-success-light-8": "#c9e5b9",
      "--el-color-success-light-9": "#f0f8ea",
      "--el-color-warning": "#b17a32",
      "--el-color-warning-light-8": "#e3c38d",
      "--el-color-warning-light-9": "#fbf5e9",
      "--el-color-danger": "#bc4b39",
      "--el-color-danger-light-8": "#e2aaa0",
      "--el-color-danger-light-9": "#fbefec",
      "--el-color-info": "#697267",
      "--el-color-info-light-8": "#c1c8be",
      "--el-color-info-light-9": "#f1f3ef",
      "--el-bg-color-page": "#fbfdf8",
      "--el-bg-color": "#ffffff",
      "--el-bg-color-overlay": "#ffffff",
      "--el-text-color-primary": "#25321f",
      "--el-text-color-regular": "#415035",
      "--el-text-color-secondary": "#6f7d63",
      "--el-text-color-placeholder": "#a0ad96",
      "--el-border-color-dark": "#cfddc4",
      "--el-border-color": "#e1ead9",
      "--el-border-color-light": "#edf3e7",
      "--el-border-color-lighter": "#f4f8ef",
      "--el-border-color-extra-light": "#f8fbf5",
      "--el-fill-color-dark": "#e7f1de",
      "--el-fill-color": "#f4faef",
      "--el-fill-color-light": "#f8fcf4",
      "--el-fill-color-lighter": "#ffffff",
      "--el-fill-color-extra-light": "#fcfef9",
      "--el-text-color-tertiary": "#a0ad96",
      "--el-shadow-sm": "0 2px 8px rgba(99, 156, 45, 0.06)",
      "--el-shadow": "0 12px 34px rgba(99, 156, 45, 0.1)",
      "--el-shadow-md": "0 18px 45px rgba(99, 156, 45, 0.13)",
      "--el-shadow-lg": "0 24px 56px rgba(99, 156, 45, 0.15)",
      "--el-shadow-xl": "0 32px 64px rgba(99, 156, 45, 0.18)",
      "--shadow-card": "0 12px 34px rgba(99, 156, 45, 0.1)",
      "--shadow-card-hover": "0 18px 45px rgba(99, 156, 45, 0.13)",
      "--shadow-dropdown": "0 18px 45px rgba(99, 156, 45, 0.13)",
      "--shadow-tab": "0 2px 8px rgba(99, 156, 45, 0.06)",
      "--shadow-primary": "0 14px 24px rgba(99, 156, 45, 0.24)",
      "--shadow-primary-hover": "0 18px 30px rgba(99, 156, 45, 0.3)",
      "--manager-relation-icon-color": "var(--el-color-primary-dark-2)",
      "--manager-relation-icon-background": "color-mix(in srgb, var(--el-color-primary) 14%, var(--el-bg-color))",
      "--manager-model-catalog-min-height": "auto",
      "--manager-modeling-panel-header-background": "var(--el-bg-color)",
      "--manager-filter-drawer-radius": "0",
    },
    dark: {
      "--el-color-primary": "#8fd04d",
      "--el-color-primary-light-3": "#a9db75",
      "--el-color-primary-light-5": "#c6e8a6",
      "--el-color-primary-light-7": "#e2f3d5",
      "--el-color-primary-light-8": "#43652d",
      "--el-color-primary-light-9": "#2a421d",
      "--el-color-primary-dark-2": "#75bd35",
      "--el-color-success": "#8fcf59",
      "--el-color-success-light-8": "#3c5f2b",
      "--el-color-success-light-9": "#253f1d",
      "--el-color-warning": "#d4a75c",
      "--el-color-warning-light-8": "#55421f",
      "--el-color-warning-light-9": "#382c17",
      "--el-color-danger": "#e07865",
      "--el-color-danger-light-8": "#5a2923",
      "--el-color-danger-light-9": "#3a1f1b",
      "--el-color-info": "#98a595",
      "--el-color-info-light-8": "#303a2e",
      "--el-color-info-light-9": "#20281f",
      "--el-bg-color-page": "#121b10",
      "--el-bg-color": "#1a2616",
      "--el-bg-color-overlay": "#21331c",
      "--el-text-color-primary": "#f2f8ee",
      "--el-text-color-regular": "#d8e6d0",
      "--el-text-color-secondary": "#aebea4",
      "--el-text-color-placeholder": "#6d7f63",
      "--el-border-color-dark": "#557346",
      "--el-border-color": "#3b5632",
      "--el-border-color-light": "#30472a",
      "--el-border-color-lighter": "#263a22",
      "--el-border-color-extra-light": "#3b5632",
      "--el-fill-color-dark": "#1d2c19",
      "--el-fill-color": "#263820",
      "--el-fill-color-light": "#2c4325",
      "--el-fill-color-lighter": "#36502e",
      "--el-fill-color-extra-light": "#3f5c35",
      "--el-text-color-tertiary": "#839378",
      "--el-shadow-sm": "0 2px 8px rgba(0, 0, 0, 0.3)",
      "--el-shadow": "0 12px 34px rgba(0, 0, 0, 0.4)",
      "--el-shadow-md": "0 18px 45px rgba(0, 0, 0, 0.5)",
      "--el-shadow-lg": "0 24px 56px rgba(0, 0, 0, 0.5)",
      "--el-shadow-xl": "0 32px 64px rgba(0, 0, 0, 0.6)",
      "--shadow-card": "0 12px 34px rgba(0, 0, 0, 0.3)",
      "--shadow-card-hover": "0 18px 45px rgba(0, 0, 0, 0.4)",
      "--shadow-dropdown": "0 18px 45px rgba(0, 0, 0, 0.4)",
      "--shadow-tab": "0 2px 8px rgba(0, 0, 0, 0.3)",
      "--shadow-primary": "0 14px 24px rgba(143, 208, 77, 0.26)",
      "--shadow-primary-hover": "0 18px 30px rgba(143, 208, 77, 0.34)",
      "--manager-relation-icon-color": "var(--el-color-primary-dark-2)",
      "--manager-relation-icon-background": "color-mix(in srgb, var(--el-color-primary) 14%, var(--el-bg-color))",
      "--manager-model-catalog-min-height": "auto",
      "--manager-modeling-panel-header-background": "var(--el-bg-color)",
      "--manager-filter-drawer-radius": "0",
    },
  },
  nodePalette: ["#639c2d", "#8bbf4a", "#d79b3b", "#58a968", "#d46b57", "#84956f"],
  edgeLabel: { labelPlacement: "center", labelAutoRotate: false },
  maxFitZoom: 1,
  dataBrowserDescription: () => "Browse and inspect data records for the current object type.",
  compactDialogs: true,
};
