import type { ModelAgentCatalog } from "@ontomato/workbench-server/logging/model-agents";

/** Model agent names and diagnosis display names from before the open-source migration (call sites and prompt-agent-catalog of b6437c86). */
export const ossModelAgents: ModelAgentCatalog = {
  roles: {
    taskPlanner: { agentName: "Standard Data Query-TaskPlanner", displayName: "1.1 Task Planner" },
    analysis: { agentName: "Standard Data Query-Analysis", displayName: "1.4 Knowledge Validator" },
    reply: { agentName: "Standard Data Query-Reply" },
    dataResolver: { agentName: "Standard Data Query-DataResolver", displayName: "3.20 Data Resolver" },
    abcDescription: { agentName: "Data Query-AbcDescription", displayName: "1.6 ABC Description Generator" },
    conclusion: { agentName: "Data Query-Conclusion", displayName: "3.2 Conclusion Generator" },
    fieldAdapter: { agentName: "Data Query-FieldAdapter", displayName: "3.3 Field Display Planner" },
    hotDataStatic: { agentName: "Data Query-HotDataStatic", displayName: "3.5 Hot Data Static Query Agent" },
    hotDataDynamic: { agentName: "Data Query-HotDataDynamic", displayName: "3.6 Hot Data Dynamic Query Agent" },
    abcHarnessAnswer: { agentName: "Data Query-AbcHarnessAnswer", displayName: "3.19 Deep Thinking Answer Polisher" },
    answerEvaluator: { agentName: "Evaluation-Answer", displayName: "3.8 Auto Evaluator" },
    followUp: { agentName: "Follow-up Assistant", displayName: "3.15 Follow-up Assistant" },
    chartPlanner: { agentName: "Chart-ChartPlanner", displayName: "3.17 Chart Planner" },
    analysisDimension: { agentName: "Deep Analysis-Dimension", displayName: "3.16 Deep Analysis Dimension Planner" },
    analysisReport: { agentName: "Deep Analysis-Report", displayName: "3.18 Deep Analysis Report Generator" },
    hotReportMatcher: { agentName: "Deep Analysis-HotReportMatcher", displayName: "3.22 Hot Report Matcher" },
    analysisLoop: { agentName: "Deep Analysis-Loop" },
    analysisLoopSubAgent: { agentName: "Deep Analysis-LoopSubAgent" },
  },
  otherDisplayNames: {
    TaskPlanner: "1.1 Task Planner",
    "Standard Data Query-Router": "1.1 Query Router",
    "Standard Data Query-Planner": "1.2 Query Orchestrator",
    "Standard Data Query-Clarification": "1.3 Intent Clarifier",
    "Standard Data Query-Visualization": "1.5 Visualization Planner",
    "API-TitleGenerator": "3.1 Title Generator",
    "Data Query-HotDataReport": "3.7 Hot Data Reporter",
    "Skill-Matcher": "3.9 Skill Matcher",
    "Skill-Executor": "3.10 Skill Executor",
    "Dashboard-ChartFieldPlanner": "3.11 Dashboard Field Planner",
    "Dashboard-AppendPlanner": "3.12 Dashboard Append Planner",
    "Dashboard-DashboardPlanner": "3.13 Dashboard Planner",
    "Dashboard-ChartAnalyzer": "3.14 Dashboard Chart Analyzer",
    "Deep Analysis-ChartGenerator": "3.17 Deep Analysis Chart Generator",
  },
  backendDisplayNames: {
    splitQuestion: "2.1 Question Analyzer",
    QUESTION_SPLITER: "2.1 Question Analyzer",
    QUESTION_SPLITER_V0: "2.1 Question Analyzer",
    QUESTION_SPLITER_V1: "2.1 Question Analyzer",
    ABC_PROGRAMMER: "2.1 ABCHarness Programmer",
    DSLCooker: "2.2 DSL Generator",
    DSL_COOKER: "2.2 DSL Generator",
    afterCalculator: "2.3 Data Analysis Expert",
    TOOL_AND_PYTHON_CALCULATOR: "2.3 Data Analysis Expert",
    questionCardInstancer: "5.2 Metric Template Operator (Judgment Generation)",
    QUESTION_CARD_INSTANCER: "5.2 Metric Template Operator (Judgment Generation)",
    questionCardGenerator: "5.3 Generic Metric Template Generator",
    QUESTION_CARD_GENERATOR: "5.3 Generic Metric Template Generator",
    READ_FUNCTION_MAKER: "5.4 Read Function Generator",
    STATIC_READ_FUNCTION_NAME_MAKER: "5.5 Instantiated Function Namer",
    READ_FUNCTION_INSTANCER: "5.6 Read Function Instantiator",
    dslDescriber: "6.1 DSL Logic Interpreter",
    DSL_DESCRIBER: "6.1 DSL Logic Interpreter",
    afterCalculateDescriber: "6.2 Post-calculation Logic Interpreter",
    AFTER_CALCULATE_DESCRIBER: "6.2 Post-calculation Logic Interpreter",
    questionChecker: "6.3 Query Logic Interpreter",
    QUESTION_CHECKER: "6.3 Query Logic Interpreter",
  },
};
