import type { WorkbenchContent } from "@ontomato/workbench-ui";
import { ossProduct } from "../../src/product";
import { ossWorkspaceArtifactText } from "../../src/workspace-artifact-text";

/**
 * Static workbench content for this edition (original values). The subgraph fence and product display name come directly
 * from this edition's Node product; the rest are the original matching rules, sentences and colours from the web source
 * before extraction, independent of the UI locale.
 */
export const workbenchContent: WorkbenchContent = {
  subgraphFence: ossProduct.subgraphFence,
  serviceDisplayName: ossProduct.serviceDisplayName,
  currentQaThreadStoragePrefix: "ontomato:current-qa-thread",
  reportPdfFilePrefix: "analysis-report_",
  comprehensiveSummaryTitles: [
    "Comprehensive Summary",
    "ملخص شامل",
    "Résumé complet",
    "Umfassende Zusammenfassung",
    "Riepilogo completo",
  ],
  defaultAgentNames: ["Universal Agent", "General Agent"],
  defaultAgentDescriptions: [
    "A general-purpose agent for all kinds of business scenarios, able to automatically decompose question dimensions and generate professional analysis reports",
    "A general-purpose agent suitable for various business scenarios, capable of automatically decomposing question dimensions and generating professional analysis reports",
  ],
  hotCardQa: {
    question: /(?:^|\n)\s*(?:[-–—*•]\s*)?question\s*:\s*(.+?)\s*(?=\n|$)/i,
    questionLine: /^[-–—*•\s]*question\s*:.+\n?/im,
    answerLine: /^[-–—*•\s]*answer\s*:?\s*\n?/im,
  },
  hotCardConditionReplacement: /original condition\[(.+?)\],?\s*replaced with:\s*(.+)/i,
  chartIntentKeywords: {
    trend: ["trend", "change"],
    proportion: ["proportion", "distribution"],
    correlation: ["correlation", "scatter"],
    visualization: ["visualization", "chart", "plot", "display chart"],
  },
  subgraphListItems: {
    split: /\r?\n|\s+(?:AND|and)\s+|[;,]/,
    empty: /^(?:none|no filter conditions|no extracted fields|null|unset|[-—–])$/i,
    join: ", ",
  },
  qcStepLabel: /^step\s*\d+$/i,
  answerSubject:
    /data results for <strong>"([^"\n]+)"<\/strong> are as follows:|(?:Based on the steps above, |For <strong>)<strong>«([^»]+)»<\/strong> the data results are as follows:|For <strong>«([^»]+)»<\/strong> the results are as follows:/g,
  skillListSeparator: ",",
  analysisMcpServerName: ossProduct.analysisMcpServerName,
  opsMcpServerName: ossProduct.opsMcpServerName,
  agentDialogDisplay: { requireAsteriskPosition: "right", fitInputWidth: true, labelWrap: true },
  analysisAgentLoadErrorSeparator: ": ",
  skillDebugEchartsInput: JSON.stringify(
    {
      data: [
        { category: "Electronics", sales: 15000 },
        { category: "Clothing", sales: 12000 },
        { category: "Food", sales: 8000 },
        { category: "Home", sales: 6000 },
      ],
      chartType: "bar",
      xField: "category",
      yField: "sales",
      title: "Sales comparison by category",
    },
    null,
    2
  ),
  observe: {
    appLogSource: ossProduct.logSource,
    promptTranscript: ossWorkspaceArtifactText,
    promptDirectoryName: ossProduct.diagnosisWorkspaceNames.prompts,
  },
  text: {
    sseConnectionFailed: "Connection failed. Please check the network or server status.",
    connectionFailed: "Connection failed",
    pptSectionFallback: "Analysis Section",
    pptOutlineFailed: "Failed to distill PPT content, please try again later.",
    createDashboardFailed: "Failed to create dashboard",
    skillsListInvalid: "Invalid skills list response format: missing skills array",
    unknownError: "Unknown error",
    runSwitcher: {
      label: "Run record switch",
      previous: "Previous run",
      next: "Next run",
    },
    feedback: {
      cancelled: "Feedback cancelled",
      cancelFailed: "Failed to cancel feedback",
      promptMessage: "Please briefly explain what you're not satisfied with, so we can improve.",
      promptTitle: "Feedback",
      submit: "Submit",
      cancel: "Cancel",
      queryPlaceholder: "e.g. inaccurate results, metrics not matching expectations, unclear expression, etc.",
      analysisPlaceholder: "e.g. inappropriate analysis dimensions, inaccurate conclusions, infeasible suggestions, etc.",
      required: "Please enter your feedback",
      thanks: "Thanks for the feedback",
      submitted: "Feedback submitted",
      submitFailed: "Failed to submit feedback",
      like: "Like",
      dislike: "Dislike",
    },
    batchDeleteFailureSuffix: (failed, total) => `(${failed}/${total})`,
    exampleFieldSeparator: ":",
    businessConfigSeparator: ": ",
    feedbackRecords: {
      sourceQa: "Query",
      sourceAnalysisTask: "Analysis Task",
      time: "Time",
      source: "Source",
      rating: "Rating",
      user: "User",
      input: "Input",
      output: "Output",
      feedback: "Feedback",
      relatedId: "Related ID",
      actions: "Actions",
      details: "Details",
      detailTitle: "Feedback Details",
      searchPlaceholder: "Search user, input, output, or feedback",
      loadFailed: "Failed to load feedback records",
      exportEmpty: "No feedback records to export",
      exportSucceeded: "Feedback records exported successfully",
      exportFailed: "Failed to export feedback records",
    },
    cardCount: (label, count) => `${label}(${count})`,
    observe: {
      autoTurnDiagnosisMessage: "Diagnose this Turn's problem.",
      welcomePrompts: {
        analyzeSystem: "Analyze system status",
        troubleshootConfig: "Troubleshoot configuration issues",
        checkLLM: "Check LLM connectivity",
        viewRecentErrors: "View recent errors",
      },
      cancelled: "Cancelled",
      fileLoadFailed: "Failed to load file content",
      largeFilePreview: (loadedSize) =>
        `File is large, only the beginning ${loadedSize} was loaded; search only covers the current preview. The full content can be viewed by downloading the artifact.`,
      restoredTestBatch: (runId) => `Restored test batch ${runId}`,
    },
  },
  console: {
    deepAnalysisConnected: "[DeepAnalysis] SSE connection established",
    deepAnalysisParseFailed: "[DeepAnalysis] Failed to parse event:",
    deepAnalysisError: "[DeepAnalysis] SSE error:",
    followUpConnected: "[FollowUp] SSE connection established",
    followUpParseFailed: "[FollowUp] Failed to parse event:",
    followUpError: "[FollowUp] SSE error:",
    followUpRunParseFailed: "[FollowUpRun] Failed to parse event:",
    loadAgentsFailed: "Failed to load analysis agents:",
    loadTasksFailed: "Failed to load task list:",
    loadTaskHistoryFailed: "Failed to load task history messages:",
    loadConversationTurnsFailed: "Failed to load regular conversation turns:",
    loadRunHistoryFailed: "Failed to load run history:",
    loadTaskDetailFailed: "Failed to load task details:",
    loadQaThreadsFailed: "Failed to load QA conversation list:",
    loadHistoryFailed: "Failed to load history messages:",
    deleteQaThreadFailed: "Failed to delete QA conversation:",
    analysisActivityInvalid: "Analysis activity violates the contract",
    analysisEventUnknown: "Unrecognized analysis event",
    loadMessagesFailed: (threadId) => `[useChat] Failed to load messages threadId=${threadId}:`,
    reportChartMarkerUnmatched: (label) => `[${label}] Report chart marker unmatched, removed from content`,
  },
  dashboard: {
    themeName: "ontomatoDashboard",
    series: ["#639C2D", "#2FA98E", "#D9A441", "#BC4B39", "#5B8CD6", "#7FA653", "#C9864E", "#4FA3D1", "#9B8CC4", "#6BA583"],
    themeColors: (isDark) => ({
      text: isDark ? "#F2F8EE" : "#25321F",
      textSecondary: isDark ? "#AEBEA4" : "#6F7D63",
      axis: isDark ? "#AEBEA4" : "#415035",
      splitLine: isDark ? "#3B5632" : "#E1EAD9",
      border: isDark ? "#3B5632" : "#E1EAD9",
      visualMap: isDark
        ? ["#2A421D", "#43652D", "#639C2D", "#8FD04D", "#C6E8A6", "#E2F3D5"]
        : ["#EFF5EA", "#D0E1C0", "#92BA6C", "#639C2D", "#4F7D24", "#33521A"],
      kPositive: isDark ? "#8FCF59" : "#63A33E",
      timelineLine: isDark ? "#3B5632" : "#D0E1C0",
      timelineAccent: isDark ? "#8FD04D" : "#92BA6C",
      timelineCheck: isDark ? "#8FD04D" : "#639C2D",
    }),
    barGradients: {
      "#639C2D": ["#92ba6c", "#639C2D"],
      "#2FA98E": ["#6ac4af", "#2FA98E"],
      "#D9A441": ["#e6c47a", "#D9A441"],
      "#BC4B39": ["#d58b7e", "#BC4B39"],
      "#5B8CD6": ["#8fb0e2", "#5B8CD6"],
      "#7FA653": ["#a6c580", "#7FA653"],
      "#C9864E": ["#d9a97f", "#C9864E"],
      "#4FA3D1": ["#8bc3e2", "#4FA3D1"],
      "#9B8CC4": ["#bfb4d8", "#9B8CC4"],
      "#6BA583": ["#97c2ab", "#6BA583"],
    },
    areaGradients: {
      "#639C2D": ["rgba(99,156,45,0.42)", "rgba(99,156,45,0.12)", "rgba(99,156,45,0.02)"],
      "#2FA98E": ["rgba(47,169,142,0.40)", "rgba(47,169,142,0.10)", "rgba(47,169,142,0.02)"],
      "#D9A441": ["rgba(217,164,65,0.38)", "rgba(217,164,65,0.10)", "rgba(217,164,65,0.02)"],
      "#BC4B39": ["rgba(188,75,57,0.40)", "rgba(188,75,57,0.10)", "rgba(188,75,57,0.02)"],
      "#5B8CD6": ["rgba(91,140,214,0.38)", "rgba(91,140,214,0.10)", "rgba(91,140,214,0.02)"],
      "#7FA653": ["rgba(127,166,83,0.38)", "rgba(127,166,83,0.10)", "rgba(127,166,83,0.02)"],
      "#C9864E": ["rgba(201,134,78,0.38)", "rgba(201,134,78,0.10)", "rgba(201,134,78,0.02)"],
      "#4FA3D1": ["rgba(79,163,209,0.38)", "rgba(79,163,209,0.10)", "rgba(79,163,209,0.02)"],
      "#9B8CC4": ["rgba(155,140,196,0.40)", "rgba(155,140,196,0.12)", "rgba(155,140,196,0.02)"],
      "#6BA583": ["rgba(107,165,131,0.38)", "rgba(107,165,131,0.10)", "rgba(107,165,131,0.02)"],
    },
    defaultAreaGradient: ["rgba(99,156,45,0.42)", "rgba(99,156,45,0.12)", "rgba(99,156,45,0.02)"],
    zoomChartTheme: "dashboard",
    loadingMask: "transparent",
    chartColors: {
      primaryRgb: "99,156,45",
      label: "#25321F",
      labelSecondary: "#6F7D63",
      radarSplitLine: "#E1EAD9",
      gaugeTrack: "#E1EAD9",
    },
    chartTooltips: {
      valueWithPercent: (value, percent) => `${value} (${percent}%)`,
      valueWithShare: (key, value, percent) => `${key}: ${value}<br/>Share: ${percent}%`,
    },
    healthReasons: {
      xAxisDataEmpty: (chart) => `${chart}: xAxis.data is empty`,
      barSeriesMissing: "bar-line: missing bar series",
      lineSeriesMissing: "bar-line: missing line series",
      barLineLengthMismatch: "bar-line: series.data length does not match xAxis.data",
      seriesDataEmpty: (chart) => `${chart}: series[0].data is empty`,
      areaLineAllZero: "area-line: series[0].data is all zeros (ECharts often renders it blank",
      areaLineLengthMismatch: (x, y) => `area-line: xAxis.data(${x}) length does not match series.data(${y})`,
      scatterIllegalPoints: (n) => `scatter: data has ${n} illegal point(s) (may contain NaN/undefined/empty x)`,
      radarIndicatorEmpty: "radar: radar.indicator is empty",
      radarValueEmpty: "radar: series[0].data[0].value is empty",
      radarTooFewDimensions: "radar: too few dimensions (≤2), the radar chart can hardly present a meaningful comparison",
      radarLengthMismatch: (indicators, values) => `radar: indicator(${indicators}) length does not match value(${values})`,
      radarIllegalMax: "radar: indicator.max has an illegal value (<=0 / non-numeric)",
      sankeyFieldsMissing: "sankey: fields missing source/target/value",
      sankeyNodesEmpty: "sankey: nodes(data) is empty",
      sankeyLinksEmpty: "sankey: links is empty",
      sankeyLinksOutsideNodes: (n) => `sankey: ${n} link(s) have source/target not in nodes`,
      sankeyAllZero: "sankey: all links.value are <= 0 (ECharts often renders it blank); consider using counts / frequencies or showing a table instead",
      sankeyIllegalValues: (n) => `sankey: ${n} link(s) have illegal value (NaN/Infinity/undefined)`,
      sankeyDuplicateEdges: (n) => `sankey: ${n} duplicate source->target edge(s) exist (consider merging/summing)`,
      illegalValues: (chart, n) => `${chart}: ${n} value(s) in data are illegal`,
      boxplotIllegalItems: (n) => `boxplot: ${n} item(s) are not a valid 5-array or contain illegal numeric values`,
      gaugeIllegalValue: "gauge: data[0].value is illegal (NaN/Infinity/undefined)",
      liquidFillIllegalValues: (n) => `liquid-fill: ${n} illegal numeric value(s) in data`,
    },
  },
};
